In [2]:
import pandas as pd
import numpy as np 
import sklearn

In [8]:
submission_format=pd.read_csv('random_digit_dataset.csv')

In [9]:
submission_format.head()

   ImageId  Label
0        1      0
1        2      0
2        3      0
3        4      0
4        5      0

In [11]:
df=pd.read_csv('train.csv')
df.head()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [15]:
x=df.drop('label',axis=1)
y=df['label']

In [24]:
from sklearn.model_selection import train_test_split as tts
x_train,x_test,y_train,y_test=tts(x,y,test_size=0.1,random_state=44)

In [25]:
from sklearn.linear_model import LogisticRegression as lr
lr_model=lr(max_iter=1000)
lr_model.fit(x_train,y_train)

C:\Users\Lalith\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=1000)

In [26]:
predictions=lr_model.predict(x_test)

In [27]:
from sklearn import metrics 
c_report=metrics.classification_report(predictions,y_test)
print(c_report)
print(metrics.accuracy_score(predictions,y_test))

              precision    recall  f1-score   support

           0       0.95      0.92      0.94       422
           1       0.96      0.94      0.95       452
           2       0.88      0.90      0.89       420
           3       0.88      0.87      0.87       435
           4       0.90      0.92      0.91       395
           5       0.83      0.85      0.84       378
           6       0.96      0.94      0.95       448
           7       0.93      0.90      0.91       402
           8       0.85      0.87      0.86       416
           9       0.86      0.88      0.87       432

    accuracy                           0.90      4200
   macro avg       0.90      0.90      0.90      4200
weighted avg       0.90      0.90      0.90      4200

0.9

In [30]:
from sklearn.naive_bayes import MultinomialNB as MNB
nb_model=MNB()
nb_model.fit(x_train,y_train)

MultinomialNB()

In [33]:
p_nb=nb_model.predict(x_test)

In [35]:
from sklearn import metrics 
c_report=metrics.classification_report(p_nb,y_test)
print(c_report)
print(metrics.accuracy_score(p_nb,y_test))

              precision    recall  f1-score   support

           0       0.94      0.92      0.93       425
           1       0.91      0.87      0.89       470
           2       0.82      0.90      0.86       389
           3       0.81      0.78      0.79       447
           4       0.72      0.82      0.77       352
           5       0.62      0.81      0.70       295
           6       0.91      0.88      0.90       453
           7       0.82      0.92      0.87       345
           8       0.76      0.66      0.71       491
           9       0.82      0.68      0.74       533

    accuracy                           0.82      4200
   macro avg       0.81      0.82      0.82      4200
weighted avg       0.82      0.82      0.82      4200

0.8164285714285714

In [37]:
from sklearn.svm import SVC as SVC
svm_model=SVC()
svm_model.fit(x_train,y_train)

SVC()

In [38]:
p_svm=svm_model.predict(x_test)

In [39]:
c_report=metrics.classification_report(p_svm,y_test)
print(c_report)
print(metrics.accuracy_score(p_svm,y_test))

              precision    recall  f1-score   support

           0       0.99      0.96      0.98       423
           1       0.99      0.98      0.99       446
           2       0.97      0.96      0.97       430
           3       0.96      0.98      0.97       425
           4       0.97      0.97      0.97       404
           5       0.96      0.97      0.97       383
           6       0.98      0.98      0.98       442
           7       0.98      0.98      0.98       385
           8       0.96      0.98      0.97       420
           9       0.97      0.97      0.97       442

    accuracy                           0.97      4200
   macro avg       0.97      0.97      0.97      4200
weighted avg       0.97      0.97      0.97      4200

0.9738095238095238